/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[Name]
  FROM [pokemonreview].[dbo].[Countries]

SET IDENTITY_INSERT Countries ON

insert into Countries (Id, Name) values (4, 'Peru')

SET IDENTITY_INSERT Countries ON


ALTER PROCEDURE INSERT_COUNTRY_SP
@NAME VARCHAR(60)
AS
BEGIN

	SET IDENTITY_INSERT Countries ON

	DECLARE @ID AS INT
	SET @ID = ISNULL((SELECT TOP 1 ID FROM COUNTRIES ORDER BY ID DESC), 0) + 1

	INSERT INTO COUNTRIES (Id, Name)
	VALUES (@ID, @NAME)

	SET IDENTITY_INSERT Countries Off

END
GO

CREATE PROCEDURE UPDATE_COUNTRY_SP
@ID INT,
@NAME VARCHAR(60)
AS
BEGIN

	UPDATE COUNTRIES
	SET NAME=@NAME
	WHERE ID=@ID

END
GO

CREATE PROCEDURE DELETE_COUNTRY_SP
@ID INT
AS
BEGIN

	DELETE COUNTRIES
	WHERE ID=@ID

END
GO

EXEC INSERT_COUNTRY_SP 'Rusia'

